name: push-main
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker-push:
    runs-on: ubuntu-24.04
    env:
      DEBIAN_TAG: 12.8-slim
      NOTEBOOK_TAG: 2024-12-09
    strategy:
      matrix:
        lang:
          - bash
          - c
          - cpp
          - csharp
          - go
          - java
          - kotlin
          - lua
          - mysql
          - perl
          - php
          - powershell
          - python
          - python-notebook
          - r
          - r-notebook
          - ruby
          - sqlite
          - swift
          - tex

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: img/Dockerfile.${{ matrix.lang }}
        push: true
        tags: ghcr.io/zetaoss/runcontainers/${{ matrix.lang }}:latest
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          DEBIAN_TAG=${{ env.DEBIAN_TAG }}
          NOTEBOOK_TAG=${{ env.NOTEBOOK_TAG }}

    - uses: actions/delete-package-versions@v5
      with: 
        package-name: runcontainers/${{ matrix.lang }}
        package-type: 'container'
        delete-only-untagged-versions: 'true'
