name: push-main
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker-push:
    runs-on: ubuntu-24.04
    env:
      DEBIAN_TAG: 12.8-slim
      NOTEBOOK_TAG: 2024-12-09
    strategy:
      matrix:
        lang:
          - bash
          - c
          - cpp
          - csharp
          - go
          - java
          - kotlin
          - mysql
          - perl
          - php
          - powershell
          - python
          - python-notebook
          - r
          - r-notebook
          - ruby
          - sqlite
          - swift
          - tex

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        tags: "type=ref,event=tag"
        custom-tags: |
          0.0.0

    - name: Log metadata for debugging
      run: echo "Tags: ${{ steps.meta.outputs.tags }}"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: img/Dockerfile.${{ matrix.lang }}
        push: true
        tags: zetaoss/runcontainers/${{ matrix.lang }}:rc,zetaoss/runcontainers/${{ matrix.lang }}-0.0.0
        build-args: |
            DEBIAN_TAG=${{ env.DEBIAN_TAG }}
            NOTEBOOK_TAG=${{ env.NOTEBOOK_TAG }}
